name: Check if branch is up-to-date

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  check-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Check if branch is up to date
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD
          if [ $? -ne 0 ]; then
            echo "Your branch is not up-to-date with main. Please rebase your branch.";
            exit 1;
          fi
